name: Pack for tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Pack
    runs-on: windows-2022 # For a list of available runner types, refer to
                          # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create zip archive
        # https://github.com/marketplace/actions/zip-release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          # e.g. PinJuke_Media_1.0.0-alpha.1.zip
          filename: PinJuke_Media_${{ github.ref_name }}.zip
          directory: .
          path: PinJuke
      - name: Upload release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          artifacts: PinJuke_Media_${{ github.ref_name }}.zip
